# Generated by Django 3.2.6 on 2021-08-31 20:00

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomFieldDataModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstUserField', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=10), size=10)),
                ('SecondUserField', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=10), size=10)),
                ('ReadyFirstUser', models.BooleanField(default=False)),
                ('ReadySecondUser', models.BooleanField(default=False)),
                ('UserTurn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_turn', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoomModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameRoom', models.CharField(max_length=100)),
                ('Active', models.BooleanField(default=True)),
                ('CreateData', models.DateTimeField(auto_now=True)),
                ('FieldData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_data', to='SeaBattle.roomfielddatamodels')),
                ('FirstUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_user', to=settings.AUTH_USER_MODEL)),
                ('SecondUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MessageModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now=True)),
                ('Message', models.CharField(max_length=200)),
                ('Room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SeaBattle.roommodels')),
                ('Sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
