version: "3.9"
services:
  redis:
    image: "redis:6.2.5"
    restart: always
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=vova
      - POSTGRES_USER=vova
      - POSTGRES_DB=qmobi
  app:
    build: .
    command: bash -c "python manage.py makemigrations & python manage.py migrate & python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - ./:/usr/src/app/
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
